truenas/iocage

iocage/lib/ioc_common.py, iocage/lib/ioc_create.py, iocage/lib/ioc_image.py, iocage/lib/ioc_plugin.py, iocage/lib/ioc_start.py, iocage/lib/iocage.py, iocage/main.py
Ticket: #37443
Ticket: #35344
Ticket: #36598
Ticket: #35838
=> Sync with master

iocage/lib/ioc_fetch.py
=> Check for host release being less than during interactive fetch

iocage/lib/ioc_check.py
=> We want unix acl's on iocage's datasets

iocage/lib/ioc_plugin.py
This allows us to freeze the INDEX and do development without users being impacted. In addition safe guard against plugins requiring new iocage features.
Ticket: #39638
=> Use branches with plugins

iocage/cli/fetch.py, iocage/lib/iocage.py
=> Allow overriding branch for plugin fetching

iocage/cli/fetch.py, iocage/lib/ioc_common.py, iocage/lib/ioc_fetch.py, iocage/lib/ioc_plugin.py
- Also commonize the method
Ticket: #39508
=> Check host release for plugins

iocage/lib/ioc_list.py
=> Strip subnet of IP4_ADDR when building plugin's portal URL (#586)

iocage_lib/ioc_start.py
This shouldn't have still existed :)
Ticket: #41084
=> Remove unused attribute

iocage_cli/debug.py, iocage_lib/ioc_debug.py, iocage_lib/iocage.py
This should help with tickets that need to supply information
Ticket: #41196
=> Add a debug command

iocage_lib/ioc_fetch.py
This fixes some logic.
Ticket: #41868
=> We want file, not http when specified

iocage_lib/ioc_common.py, iocage_lib/ioc_create.py, iocage_lib/ioc_plugin.py
- Fix upgrading for plugins
- Fix jail creation to be basejails for plugins (They were before, but not actually removing any data)
Ticket: #41320
=> Creating duplicate plugins now name them plugin_NUM

iocage_lib/ioc_exec.py
=> Be less nice for plugin pkg's clogging up stdout

iocage/cli/create.py, iocage/cli/fetch.py, iocage/lib/ioc_common.py, iocage/lib/ioc_fetch.py, iocage/lib/ioc_plugin.py
=> Cherry pick interactive host_release check for fetch

iocage_lib/iocage.py
This was incorrectly calling None on API usage.
Ticket: #42359
=> Fix callback usage in lib/iocage

iocage_lib/ioc_exec.py
Before we merge this, waiting to see if @jsegaert can replicate his original issue with this commit.
Ticket: #42018
=> Make some plugin exec changes to hopefully address plugin output missing

iocage_lib/ioc_create.py
This commit fixes a bug which caused an exception when trying to install plugins or packages with no packages specified to be installed.
Ticket: #44735
=> Bug fix for installing packages

iocage_lib/ioc_plugin.py
This allows private repos to be used as plugins.
Ticket: #42653
=> Fix usage of git@ repos

iocage_lib/ioc_plugin.py
Last commit needed for that ticket.
Ticket: #42653
=> Initialize reference to repo after succesful porcelain.pull() (#606)

iocage_lib/ioc_destroy.py
This commit adds a try catch block to a snippet where while removing a file may raise an exception as it might not exist in the first place.
Ticket: #45805
=> Improved error handling

iocage_lib/ioc_common.py, iocage_lib/ioc_exceptions.py, iocage_lib/ioc_json.py
=> Use a specific exception for pool activation issues

iocage_lib/ioc_create.py, iocage_lib/ioc_exec.py, iocage_lib/ioc_fetch.py, iocage_lib/ioc_plugin.py, iocage_lib/ioc_upgrade.py
=> Be a better env...izen. Less pollution!

iocage_lib/ioc_create.py, iocage_lib/ioc_plugin.py
Currently we just assume it succeeds or fails, when it could be a slight transient issue.
Ticket: #44834
=> Retry on pkg and pkg install failures

iocage_lib/ioc_start.py
This works much like dhcp, just easier if you have an ipv6 network. Just set the ip6_addr to 'vnet0|accept_rtadv'
Ticket: #40468
=> Add rtsold support

iocage_lib/ioc_common.py, iocage_lib/ioc_stop.py
Previous behavior was borked. It now works.
Ticket: #48449
=> Fix exec_pre|post stop

iocage_lib/ioc_json.py, iocage_lib/ioc_start.py
Original authors: @overhacked and @jsegaert
Ticket: #48457
=> Add "allow_mlock" as a new property

iocage_lib/ioc_check.py
Previous behavior could cause us headaches if exporting and importing other pools. In addition it's heavily overengineered.
Ticket: #41268
=> Decomplicate things and just use pool/iocage as mount

iocage_lib/ioc_debug.py
=> We want the jails fstab in debug

iocage_lib/ioc_create.py
=> Don't raise a pkg error if it succeeds after the first install

iocage_lib/ioc_create.py
=> STABLE - Don't raise a pkg error if it succeeds after the first install

iocage_lib/ioc_debug.py
=> STABLE - We want the jails fstab in debug

iocage_lib/ioc_json.py
=> Catch any exceptions trying to load freebsd-version during check_config

iocage_lib/ioc_json.py
=> STABLE: Catch any exceptions trying to load freebsd-version during check_config

iocage_lib/ioc_debug.py
Previous behavior infinitely appended data.
Also add netstat to host debug and correct df header
FreeNAS Ticket: #56202
=> STABLE: Debugs now correctly start fresh

iocage_lib/ioc_debug.py
=> STABLE: Include templates in debug

iocage_lib/ioc_create.py, iocage_lib/ioc_start.py
=> STABLE: Properly set rtsold during creation

iocage_lib/ioc_start.py
=> Add accept_rtadv and autoconf to jail nic when accept_rtadv is set

iocage_lib/ioc_json.py, iocage_lib/iocage.py
- Add missing return for default prop setting
FreeNAS Ticket: #56556
=> Use default gateway for mac_prefix or generate one

iocage_lib/ioc_exec.py, iocage_lib/iocage.py
=> tkt-59193: Use en_US.UTF-8 or users LANG by default for console/exec

iocage_lib/ioc_common.py, iocage_lib/iocage.py
=> tkt-59823: Use the first item for dicts sent to get recursive

iocage_lib/ioc_common.py
Spotted by @jsegaert over in iocage/iocage
=> tkt-59823: FIx get -r

iocage_lib/ioc_common.py, iocage_lib/ioc_create.py, iocage_lib/ioc_fetch.py, iocage_lib/ioc_upgrade.py, iocage_lib/iocage.py
In addition basejails will now all see the new patch level upon one updating that shares the same release.
Ticket: #59442
=> tkt-59442: Update now correctly updates the release property with the patch level

iocage_lib/ioc_create.py
=> tkt-60165: Correctly mount basejail and umount basejails during cloning

iocage_lib/ioc_upgrade.py
=> tkt-59751: Fix bad path being sent to upgrade

iocage_lib/ioc_create.py
=> tkt-60525: Destroy leftover snapshot for thick jail creation

iocage_lib/ioc_common.py, iocage_lib/ioc_fetch.py
Also send callbacks if one was supplied even if silent is set.
FreeNAS Ticket: #54717
=> tkt-54717: Move progress out of update_progress for fetch

iocage_lib/ioc_json.py, iocage_lib/ioc_list.py, iocage_lib/iocage.py
Possibly more can be moved into the new classes, but for now these were needed.
- Fix bad release prop setting
- Reduce all usage of getting pool and iocroot many times
Closes iocage#700
FreeNAS Ticket: #60768
=> tkt-60768: Break ioc_json into more classes

iocage_cli/create.py, iocage_cli/fetch.py, iocage_lib/ioc_create.py, iocage_lib/ioc_json.py, iocage_lib/ioc_plugin.py, iocage_lib/iocage.py
This will cause the configuration to not inherit the hosts defaults.json, which is the default behavior.
FreeNAS Ticket: #60774
=> tkt-60774: Add thick configuration for creation of jails and plugins

iocage_lib/iocage.py
This commit fixes a bug which was affecting fetch from fetching releases and also thick config plugins couldn't be created.
Ticket: #61191
=> tkt-61191: Bug fix for iocage fetch

iocage_lib/ioc_json.py
=> tkt-61974: Allow auto to be set for vnet_default_interface

iocage_lib/ioc_json.py
This alleviates issues of configuration version incrementing along with possibly wanting to remove properties that were set. Like ip4_addr and such.
FreeNAS TIcket: #57876
=> STABLE: Set templates to read/write for json writing and back to readonly

iocage_lib/ioc_exec.py, iocage_lib/iocage.py
git cherry-pick bbb564561b27147ddecfd2adeffc1dba395bb47d
Ticket: #59193
=> tkt-59202: Use en_US.UTF-8 or users LANG by default for console/exec (by skarekrow)

iocage_lib/ioc_json.py, iocage_lib/iocage.py
- Add missing return for default prop setting
FreeNAS Ticket: #56556
=> STABLE: Use default gateway for mac_prefix or generate one

iocage_lib/ioc_create.py
git cherry-pick e54c9e79ee5cab7a0108bc85df41146568c936ed
We were missing a split and the rc.conf entry had a typo.
Ticket: #58794
=> tkt-60480: Fix hostname in rc.conf and /etc/hosts generation (by skarekrow)

iocage_lib/ioc_common.py, iocage_lib/ioc_fetch.py
Also send callbacks if one was supplied even if silent is set.
FreeNAS Ticket: #54717
=> tkt-60705: Move progress out of update_progress for fetch (by skarekrow)

iocage_lib/iocage.py
=> tkt-61659: Re-set self.rc on restart

iocage_lib/iocage.py
=> tkt-62604: Re-set self.rc on restart (by skarekrow)

iocage_lib/ioc_check.py, iocage_lib/ioc_json.py
=> tkt-63099: Do not create default configuration if checking datasets

iocage_lib/ioc_list.py
=> tkt-63432: Add templates to quick listing

iocage_lib/ioc_start.py
=> tkt-64341: Fix bad character that was merged

iocage_lib/ioc_plugin.py
=> tkt-67510: If a plugin's MANIFEST cannot be found directly, we glob for it (by skarekrow)

iocage_lib/ioc_json.py
=> Fix error message for corrupted default.json (11.2-stable)

iocage_lib/iocage.py
FreeNAS Ticket: #72619
Closes #618
=> tkt-72627: Create a snapshot for update (by skarekrow)

iocage_lib/ioc_json.py
=> tkt-70993: Correct bad validation for 11.2-stable

iocage_lib/ioc_check.py
FreeNAS Ticket: #70122
Closes #810
=> tkt-70435: Require a mountpoint on parent iocage dataset (by skarekrow)

iocage_lib/ioc_plugin.py
DHCP grabbed it's IP too late as the jail was not running. Starting it now, and moving that IP logic.
FreeNAS Ticket: #75306
=> tkt-75306: IOCAGE_PLUGIN_IP now works with DHCP

iocage_cli/__init__.py, iocage_lib/ioc_exceptions.py, iocage_lib/ioc_fstab.py
These all combine into fixing Ticket: #76864 and preventing other sadness from being filed later on.
=> tkt-76864: Backport fstab fixes

iocage_lib/ioc_exceptions.py
=> tkt-77305: Add missing import

iocage_lib/ioc_plugin.py
=> tkt-77494: No longer ask for eol when fetching a missing RELEASE for plugins (by skarekrow)

iocage_lib/ioc_common.py
git cherry-pick 37b8782b16cd876818ab4395d2b5d1b4e3aed219
git cherry-pick 4e4a4ff7d709a7c492d25eed8a65757638835c95
git cherry-pick c835b584358d2f35891c428c8f8f5085bd67f7c7
FreeNAS Ticket: #77377
=> tkt-77701: Treat stdout being closed as not a tty (by skarekrow)

iocage_lib/ioc_json.py
=> tkt-78097: Use pathlib to accurately track if freebsd-version exists

iocage_cli/fstab.py, iocage_lib/ioc_fstab.py
=> Backport fstab changes from NAS-101252

iocage_cli/__init__.py
Signed-off-by: Brandon Schneider <brandon@ixsystems.com>
=> Update version string

iocage_lib/ioc_fstab.py
NAS-101531
Signed-off-by: Brandon Schneider <brandon@ixsystems.com>
=> NAS-101531 / 11.2 / Do not test len of None (by skarekrow)

iocage_lib/ioc_start.py
NAS-101760
Signed-off-by: Brandon Schneider <brandon@ixsystems.com>
=> NAS-101760 / 11.2 / Allow dots in jail name (#935)

iocage_lib/ioc_plugin.py
This commit adds error messages if updating of a git repo fails for some reason.
=> NAS-102929 / 11.2 / Improve error messages while cloning/pulling git repo (by sonicaj)

iocage_lib/ioc_list.py
=> NAS-104039 / 12 / Make sure we don't error out listing jails if a jail doesn't have roo… (by sonicaj)

iocage_lib/ioc_plugin.py
=> NAS-104038 / 12 / Show user update is in progress and what issues occur if any after ba… (by sonicaj)

iocage_lib/ioc_list.py
=> NAS-104039 / 11.3 / Make sure we don't error out listing jails if a jail doesn't have roo… (by sonicaj)

iocage_lib/ioc_plugin.py
=> NAS-104038 / 11.3 / Show user update is in progress and what issues occur if any after ba… (by sonicaj)

iocage_lib/ioc_image.py
=> NAS-104129 / 12 / Reset cache after importing a jail (by sonicaj)

iocage_lib/ioc_image.py
=> NAS-104129 / 11.3 / Reset cache after importing a jail (by sonicaj)

iocage_lib/ioc_json.py
=> NAS-104172 / 12 / Correct iocage behavior when it will try to set zfs dataset propertie… (by sonicaj)

iocage_lib/ioc_json.py
=> NAS-104172 / 11.3 / Correct iocage behavior when it will try to set zfs dataset propertie… (by sonicaj)

iocage_lib/ioc_json.py
=> NAS-104278 / 12 / Validate/update invalid fstab file before updating jail configuration (by sonicaj)

iocage_lib/ioc_json.py
=> NAS-104278 / 11.3 / Validate/update invalid fstab file before updating jail configuration (by sonicaj)

iocage_lib/ioc_list.py
=> NAS-104308 / 12 / Correctly retrieve admin portal for different nat interface (by sonicaj)

iocage_lib/ioc_list.py
=> NAS-104308 / 11.3 / Correctly retrieve admin portal for different nat interface (by sonicaj)

iocage_lib/ioc_json.py
=> NAS-105281 / 12.0 / Add ability to retrieve default only props (by sonicaj)

iocage_lib/ioc_json.py
=> NAS-105281 / 11.3 / Add ability to retrieve default only props (by sonicaj)

iocage_lib/ioc_common.py, iocage_lib/ioc_start.py
=> NAS-105342 / 12.0 / Pass networking configuration to plugin

iocage_lib/ioc_common.py, iocage_lib/ioc_start.py
git cherry-pick -x 10afc45658981c8df122fd22dbf555262d6e999f
git cherry-pick -x d9830f553bff866e560fa57edd61967622284968
=> NAS-105342 / 11.3 / Pass networking configuration to plugin (by sonicaj)

iocage_lib/ioc_fstab.py
=> NAS-105327 / 12.0 / Allow reading fstab for a template (by sonicaj)

iocage_lib/ioc_fstab.py
=> NAS-105327 / 11.3 / Allow reading fstab for a template (by sonicaj)

iocage_lib/ioc_plugin.py, iocage_lib/iocage.py
=> NAS-105386 / 12.0 / Restart plugin after update (by sonicaj)

iocage_lib/ioc_fetch.py
=> NAS-105387 / 12.0 / Mount/Umount properly during iocage update failure (by sonicaj)

iocage_lib/ioc_plugin.py, iocage_lib/iocage.py
=> NAS-105386 / 11.3 / Restart plugin after update (by sonicaj)

iocage_lib/ioc_fetch.py
=> NAS-105387 / 11.3 / Mount/Umount properly during iocage update failure (by sonicaj)

iocage_lib/ioc_check.py
…een created
There can be a race condition where it's possible that iocage datasets were created before another call was running and was just going to create them itself.
=> NAS-105405 / 11.3 / Make sure we donot attempt to create iocage dataset if it's already b… (by sonicaj)

iocage_lib/ioc_check.py
…een created
There can be a race condition where it's possible that iocage datasets were created before another call was running and was just going to create them itself.
=> NAS-105405 / 12.0 / Make sure we donot attempt to create iocage dataset if it's already b… (by sonicaj)

iocage_lib/ioc_start.py
=> NAS-105406 / 12.0 / Give preference to CARP addresses when executing prestart hook

iocage_lib/ioc_plugin.py
This commit fixes a race condtion where multiple threads could potentially try to clone a repository which would fail as git would not be able to acquire it's own lock and the operation in progress by the user would fail
=> NAS-105422 / 12.0 / Fix race condition between multiple threads trying to clone (by sonicaj)

.travis/flake8.sh, iocage_lib/ioc_common.py, iocage_lib/ioc_list.py, iocage_lib/ioc_start.py
=> NAS-105582 / 12.0 / Use CARP IP for writing NAT ipfw rules

.travis/flake8.sh, iocage_lib/ioc_common.py, iocage_lib/ioc_list.py, iocage_lib/ioc_start.py
git cherry-pick -x 62bf92cdbca23cc1f37cf19d5bfabf4f1a4216b9
git cherry-pick -x 9264e0db1ff2a7ea6a155f019b5e9ad95567940c
git cherry-pick -x f2f8d4b42e4f3c2c35edf8185bf200c53b2e5242
git cherry-pick -x 98727a39dd47305a7be421b25b822dca9b6e4a3e
git cherry-pick -x 6eb626129a97af25bd200fe6f9b0f7251e8d47e6
=> NAS-105582 / 11.3 / Use CARP IP for writing NAT ipfw rules (by sonicaj)

iocage_lib/ioc_start.py
=> Donot make start fatal if default iface not found

iocage_lib/ioc_json.py
=> NAS-105604 / 12.0 / Handle edge case where retrieved mac_prefix can be an interface name (by sonicaj)

iocage_lib/ioc_plugin.py
This commit fixes a race condtion where multiple threads could potentially try to clone a repository which would fail as git would not be able to acquire it's own lock and the operation in progress by the user would fail
=> NAS-105422 / 11.3 / Fix race condition between multiple threads trying to clone (by sonicaj)

iocage_lib/ioc_json.py
=> NAS-105604 / 11.3 / Handle edge case where retrieved mac_prefix can be an interface name

iocage_lib/ioc_common.py, iocage_lib/ioc_list.py, iocage_lib/ioc_plugin.py, iocage_lib/ioc_start.py, iocage_lib/ioc_upgrade.py
git cherry-pick -x fdeaed4308a2f43c1b92808ff7cdcd423aa4aa94
git cherry-pick -x c8e6ecbe1324c44d27aed1548f427618028432ab
=> NAS-106122 / 12.0 / Show correct admin portal in post plugin installation for NAT based plugins (by sonicaj)

iocage_lib/ioc_create.py
This commit fixes an issue where if mac_prefix is not explicitly defined and the one set in defaults.json is an invalid one, we move forward using the invalid one. This is not desired, so if mac_prefix is not specified by the user and the one found in defaults.json is invalid, we on jail creation use a valid one then logging a warning. A more strict approach has not been taken in this case because it would require users to correct the mac prefix in defaults.json ( which would have wrong value if was created at a time before iocage patched the issue ) and any existing jails depending on that will inherit that change which in many environments will not be desired if the env depends on the mac address of the jail.
=> NAS-106254 / 12.0 / Make sure valid mac prefix is used when creating jails (by sonicaj)

iocage_lib/ioc_create.py
This commit fixes an issue where if mac_prefix is not explicitly defined and the one set in defaults.json is an invalid one, we move forward using the invalid one. This is not desired, so if mac_prefix is not specified by the user and the one found in defaults.json is invalid, we on jail creation use a valid one then logging a warning. A more strict approach has not been taken in this case because it would require users to correct the mac prefix in defaults.json ( which would have wrong value if was created at a time before iocage patched the issue ) and any existing jails depending on that will inherit that change which in many environments will not be desired if the env depends on the mac address of the jail.
=> NAS-106254 / 11.3 / Make sure valid mac prefix is used when creating jails (by sonicaj)

iocage_lib/ioc_json.py, iocage_lib/iocage.py, iocage_lib/pools.py
=> NAS-106544 / 12.0 / Ensure locked root dataset or locked iocage dataset is not used by iocage (by sonicaj)

iocage_lib/ioc_json.py
=> NAS-106546 / 12.1 / Move radarr/sonarr to community repo (by sonicaj)

iocage_lib/ioc_start.py
=> NAS-106547 / 12.1 / Clear out dhcp/accept_rtadv entries from rc.conf if DHCP is disabled (by sonicaj)

iocage_lib/ioc_json.py
=> NAS-106610 / 12.1 / Move plugins from official plugins list to community plugins (by sonicaj)

iocage_lib/ioc_plugin.py
=> Do not check ABI difference on upgrades

iocage_lib/ioc_json.py
=> NAS-106546 / 11.3 / Move radarr/sonarr to community repo (by sonicaj) (by bugclerk)

iocage_lib/ioc_plugin.py
=> NAS-106634 / 12.1 / Do not check ABI difference on upgrades (by sonicaj)

iocage_lib/ioc_start.py
=> NAS-106547 / 12.0 / Clear out dhcp/accept_rtadv entries from rc.conf if DHCP is disabled

iocage_lib/ioc_upgrade.py
This PR introduces changes where we automatically re-install pkg to work around an upstream issue - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239498
=> NAS-106770 / 12.1 / Automatically install pkg after upgrade to 12 for jails (by sonicaj)

iocage_lib/ioc_upgrade.py
This PR introduces changes where we automatically re-install pkg to work around an upstream issue - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239498
=> NAS-106770 / 12.0 / Automatically install pkg after upgrade to 12 for jails (by sonicaj)

iocage_lib/ioc_plugin.py
=> Backport plugin version retrieval changes

iocage_lib/ioc_start.py
=> NAS-106850 / 12.1 / Correctly split on cases where there are multiple '=' (by sonicaj)

iocage_lib/ioc_start.py
=> NAS-106850 / 12.0 / Correctly split on cases where there are multiple '=' (by sonicaj)

iocage_lib/ioc_fetch.py
Original PR: https://github.com/iocage/iocage/pull/1204
=> NAS-107235 / 12.0 / Error out update in case of malformed freebsd-update.conf (by sonicaj)

iocage_lib/cache.py, iocage_lib/dataset.py, iocage_lib/ioc_check.py, iocage_lib/ioc_common.py, iocage_lib/ioc_json.py, iocage_lib/ioc_list.py, iocage_lib/ioc_plugin.py, iocage_lib/iocage.py, iocage_lib/release.py, iocage_lib/resource.py, iocage_lib/zfs.py
git cherry-pick -x 2dd416018f196d0b1d10908a5f5501c2446ebd14
git cherry-pick -x 151e5a5d91f0b0a98ddad3d741af0e6add70736e
Original PR: https://github.com/iocage/iocage/pull/1205
=> NAS-107346 / 12.0 / Improve iocage library speed by efficiently handling cache (by sonicaj)

iocage_cli/list.py
=> NAS-107641 / 12.0 / Bug fix for iocage list -h

iocage_lib/iocage.py
For plugin jails, we should make updating the jail release itself optional as it's possible that the release is already up to date to it's latest patch level and trying to update it again would mean running into an error saying jail is already up to date.
=> NAS-107914 / 12.0 / Make updating jail optional for plugins

iocage_lib/ioc_image.py
Changes taken from iocage/iocage commit 2a1685bcaba96917c79a7e4a909dac5c6926826a
=> NAS-107945 / 12.0 / Import image in chunks

iocage_lib/iocage.py
=> Bug fix for updating regular jails

iocage_lib/cache.py
=> NAS-107688 / 12.0 / Correctly retrieve dependents of a dataset

iocage_lib/pools.py
=> NAS-108748 / 12.0 / Allow activating a degraded pool if it has jails running from it

iocage_lib/ioc_image.py
=> NAS-109100 / 12.0 / Only retrieve datasets while exporting a jail

iocage_lib/iocage.py
This commit adds changes to intelligently update/upgrade plugin based on what's required for the plugin as the user should not be making a distinction between update/upgrade for a plugin because they are managed by us.
=> NAS-112048 / 12.0 / Add endpoint to update/upgrade plugin intelligently
