iocage/lib/ioc_create.py
iocage/lib/ioc_plugin.py
iocage/lib/ioc_start.py

Requires the iocage side of #36948 (https://github.com/freenas/iocage/pull/9)  to be merged before this
------
- Return a more useful pkg error
- Show more information about the install process
- General formatting improvements
- Tear down jail if DHCP fails
- Tear down jail if VNET fails
- Tear down jail if pkg upgrade fails in plugin installs (required for mismatched ABI errors from previous pkg)
Ticket: #40106

Check DNS for plugins

---

iocage_cli/fetch.py
iocage_lib/ioc_plugin.py
iocage_lib/iocage.py

This commit adds support for deleting jails by default incase a plugin install fails. However a user can still have the jail intact if a flag is specified for that behaviour.
Ticket: #41694

Delete jails in case of plugin install failure

---

iocage_lib/ioc_common.py
iocage_lib/ioc_plugin.py
iocage_lib/ioc_start.py

- DHCP is much more flexible now
- Plugins are able to have devfs rules specified in their manifests
- Plugin manifests are kept around for devfs rules now, possibly more fun later
Ticket: #42593

Change devfs rule generation

---

iocage_lib/ioc_plugin.py

Most plugins that have more then one IP use VNET, so this assumes the first interface to be the default one.
Ticket: #42641

Only show one interface for the plugin IP

---

iocage_lib/iocage.py

This commit fixes a bug which caused iocage to raise an exception incase an edit/removal was required by index only and destination field was passed on as null in fstab.
Ticket: #45783

Fixed a bug in fstab

---

iocage_lib/ioc_create.py

This commit fixes a potential bug which possible arose due to a race condition when the system was unable to find a newly created file. The original referenced issue couldn't be reproduced but necessary steps have been taken to avoid this behavior in this commit.
Ticket: #43119

Potential Bug fix for jail creation

---

iocage_lib/ioc_list.py
iocage_lib/ioc_plugin.py

This would be fatal if they didn't supply an interface, in addition we don't care about the interface here, so these block's aren't useful.
Ticket: #41670

Test variable before splitting again, honor IP only for plugin install

---

iocage_lib/ioc_create.py
iocage_lib/ioc_json.py
iocage_lib/ioc_start.py

This commit improves validation for vnet mac props by ensuring that a valid mac address is specified each time with taking into account that the addresses aren't repeated.
Ticket: #45838

Improve validation for VNET MAC Fields

---

iocage_lib/ioc_common.py

add path 'ulpt[0-9]*' mode 666 and such.
Ticket: #46920

Fix devfs rules that have a bracket

---

iocage_lib/ioc_start.py

This commit fixes a bug which resulted in a traceback when a comma was present in the mac addresses.
Ticket: #47085

Bug fix for MAC Addresses

---

iocage_lib/ioc_create.py
iocage_lib/ioc_json.py
iocage_lib/ioc_start.py

This commit adds support for customizing the default interface for vnet which should be attached on the relevant bridge. It updates the properties of the jails by adding a new property which is used when starting vnet jails.
Ticket: #40484

Make default interface for vnet customizable

---

iocage
iocage_lib/ioc_list.py

This commit fixes a bug where in case a jail's networking was broken, we wouldn't be able to list down all the jails as that jail would leave a traceback.
Ticket: #47151

Bug fix for listing jails

---

iocage_cli/fetch.py

Previously it required a boolean.
Ticket: #48416

keep_jail_on_failure should be a flag

---

iocage_lib/ioc_json.py
iocage_lib/ioc_start.py

This can be either 0 or 1. This change will also make devfs rulesets individual for each jail that sets dhcp or allow_tun. But it also means you can combine them now.
Ticket: #40872

Allow unhiding tun devices with a custom prop "allow_tun"

---

iocage_lib/iocage.py

Upstream required -l to be passed to jexec to clean the environment. Otherwise it was just for the jail initialization.
Ticket: #48581

exec_clean now affects exec as expected.

---

Makefile
iocage
iocage_cli/exec.py
iocage_lib/ioc_common.py
iocage_lib/ioc_create.py
iocage_lib/ioc_exceptions.py
iocage_lib/ioc_exec.py
iocage_lib/ioc_fetch.py
iocage_lib/ioc_json.py
iocage_lib/ioc_plugin.py
iocage_lib/iocage.py
setup.py

iocage side of #37742, still requires plugin work in freenas/freenas.
Use python dns.resolver
Drop other types of DNS tests
Make Exec a generator
New Exception type CommandFailed for Exec failures
Use Exec for RELEASE updating along with jail
Break console out of Exec
Log update progress now (means colors as well)
Ticket: #37742

Large rework to Exec interface

---

iocage_cli/pkg.py
iocage_lib/ioc_exec.py
iocage_lib/ioc_fetch.py
iocage_lib/ioc_plugin.py
iocage_lib/ioc_upgrade.py
iocage_lib/iocage.py

iocage side of 50167 and 51863

Upgrade progress support for jails and plugins/basejails 

---

iocage_lib/ioc_common.py

iocage relies on these being handled, and the other callbacks might not care.
Ticket: #52459

Ignore callback for exceptions

---

iocage_lib/ioc_plugin.py

This commit makes sure that jails are deleted by default in all exceptions that occur.
Ticket: #50519

Delete jails for all exceptions in case of jail failure by default

---

iocage_lib/ioc_start.py

This commit makes sure that we raise exception via proper iocage channels incase an old invalid mac address entry exists in the system.
Ticket: #53674

Raise proper exception for old invalid Mac addresses

---

iocage_lib/ioc_exec.py
iocage_lib/ioc_fetch.py
iocage_lib/ioc_upgrade.py
iocage_lib/iocage.py

In addition we also no longer set None for a clean env on exec/console. Not setting TERM resulted in some odd entries like su or screen that don't always play nice with utilities inside the jail.
FreeNAS Ticket: #52237

Add TERM to default clean envs

---

iocage_lib/ioc_exec.py
iocage_lib/ioc_fetch.py
iocage_lib/ioc_upgrade.py
iocage_lib/iocage.py

In addition we also no longer set None for a clean env on exec/console. Not setting TERM resulted in some odd entries like su or screen that don't always play nice with utilities inside the jail.
FreeNAS Ticket: #52237

STABLE: Add TERM to default clean envs

---

iocage_lib/ioc_debug.py
iocage_lib/ioc_exceptions.py
iocage_lib/ioc_json.py
iocage_lib/ioc_list.py
iocage_lib/iocage.py

Previous behavior was to immediately die
- Add 3 new exceptions for misconfigured jails
- Start to use them in ioc_json
- Show corrupt jails in iocage list
- Return corrupt jails in get all recursive API with default key values being replaced with N/A (FreeNAS focused)
FreeNAS Ticket: #51997

Continue on corrupt jail configurations

---

iocage_lib/ioc_debug.py
iocage_lib/ioc_exceptions.py
iocage_lib/ioc_json.py
iocage_lib/ioc_list.py
iocage_lib/iocage.py

Previous behavior was to immediately die
- Add 3 new exceptions for misconfigured jails
- Start to use them in ioc_json
- Show corrupt jails in iocage list
- Return corrupt jails in get all recursive API with default key values being replaced with N/A (FreeNAS focused)
FreeNAS Ticket: #51997

STABLE: Continue on corrupt jail configurations

---

iocage_lib/ioc_start.py

This didn't allow dhcp enabled jails to actually start dhclient.
FreeNAS Ticket: #56844

Fix bad indent

---

iocage_lib/ioc_image.py

Jails created with a _ in their name (plugins for example) would fail as the split was too greedy.
FreeNAS Ticket: #56211

Make import more robust with handling naming

---

iocage_lib/ioc_common.py

This would have user RELEASE datasets that reused the major of a release to either override or be overridden by the RELEASE.
FreeNAS Ticket: #57861

Add enumeration to internal sorting for RELEASEs

---

iocage_lib/ioc_json.py

This alleviates issues of configuration version incrementing along with possibly wanting to remove properties that were set. Like ip4_addr and such.
FreeNAS TIcket: #57876

Set templates to read/write for json writing and back to readonly

---

iocage_cli/migrate.py
iocage_cli/snapremove.py
iocage_lib/ioc_create.py
iocage_lib/ioc_destroy.py
iocage_lib/ioc_exec.py
iocage_lib/ioc_json.py
iocage_lib/ioc_list.py
iocage_lib/ioc_plugin.py
iocage_lib/ioc_start.py
iocage_lib/ioc_stop.py
iocage_lib/ioc_upgrade.py
iocage_lib/iocage.py
tests/unit_tests/1000_lib_start_test.py

- Fix bad behavior with host_strict_id_check
- Simplify config upgrades
- Configurations now show what the user has set, with a few jail specific properties
- Removed many instances of passing configuration to certain classes
- We now merge the default props with the jail props when reading them in via json_get_value('all')
FreeNAS Ticket: #58149

Write partial configurations by default

---

iocage_lib/ioc_json.py

Thick/Empty jails and warden migration jails from FreeNAS fall in this category.
Ticket: #58365

Fallback to using the jails freebsd_version if the RELEASE one fails

---

iocage_lib/ioc_json.py

This avoids wasted time going through the motions. Also allow users to use list, get and such without requiring root unless a configuration version changed (spotted by @jsegaert)
FreeNAS Ticket: #58617

Skip checking configuration if the versions match

---

iocage_lib/ioc_common.py
iocage_lib/ioc_create.py
iocage_lib/ioc_start.py

Instead of warning the user they need these, we set them for the user in addition to the warning.
Also show all missing props during start.
Ticket: #53334

Correctly add bpf to devfs rules, change creation warnings for props

---

iocage_lib/ioc_create.py

Without doing so plugins cannot be created. This is a result of jails no longer storing every property.

Need 'type' for plugins

---

iocage_lib/ioc_json.py

Thick/Empty jails and warden migration jails from FreeNAS fall in this category.
Ticket: #58365

STABLE: Fallback to using the jails freebsd_version if the RELEASE one fails

---

iocage_lib/ioc_json.py
iocage_lib/ioc_start.py

If the jail is running, the devfs ruleset will never be correct unless a user is supplying a manual one.
Ticket: #59841

tkt-59841: Show devfs ruleset when starting and return correct one

---

iocage_lib/ioc_fetch.py
iocage_lib/iocage.py

This has the additional advantage of updating basejails when the release that is fetched is updated.
Improvement suggested by @jsegaert.
Ticket: #59442

tkt-59442: Move updating basejails to base module ioc_fetch

---

iocage_lib/ioc_create.py

We were missing a split and the rc.conf entry had a typo.
Ticket: #58794

tkt-58794: Fix hostname in rc.conf and /etc/hosts generation

---

iocage_lib/ioc_create.py
iocage_lib/ioc_upgrade.py

Remove unused variable in IOCUpgrade
FreeNAS Ticket: #60534

tkt-60534: Unneeded cloned_release property kept around with thick jails

---

iocage_cli/create.py
iocage_lib/iocage.py

This commit fixes a bug where we were not able to create count jails when a valid uuid was supplied as a name. Apart from that this commit enforces that count flag cannot be used with uuid flag and removes force option from create command as it is not used anywhere.
Ticket: #61551

tkt-61551: Bug fix for always creating jails with name and count flags

---

iocage_lib/ioc_start.py

This commit fixes a bug where if 0.0.0.0 was the ip address acquired by the jail, an error was not raised by iocage.
Ticket: #61983

tkt-61983: Raise DHCP error if DHCP not configured

---

iocage_lib/ioc_image.py

Jails created with a _ in their name (plugins for example) would fail as the split was too greedy.
FreeNAS Ticket: #56211

STABLE: Make import more robust with handling naming

---

iocage_lib/ioc_common.py

This would have user RELEASE datasets that reused the major of a release to either override or be overridden by the RELEASE.
FreeNAS Ticket: #57861

STABLE: Add enumeration to internal sorting for RELEASEs

---

iocage_lib/ioc_common.py
iocage_lib/ioc_create.py
iocage_lib/ioc_start.py

Instead of warning the user they need these, we set them for the user in addition to the warning.
Also show all missing props during start.
Ticket: #53334

STABLE: Correctly add bpf to devfs rules, change creation warnings for props

---

iocage_lib/ioc_create.py

This allows the user to customize their rc.conf that is deployed to jails. Important to customize for environments.
Behavior:
- If jail is being created from a template, it will use the templates rc.conf instead of the default_rc.conf. 
- If jail is being created from a RELEASE, it will use the default_rc.conf located in the iocage mountpoint.
- Fix bad sendmail default

tkt-62046: Use default rc.conf file instead of builtin boilerplate

---

iocage_lib/ioc_create.py

Currently this is leaving it enabled for jails, which is not desired.
FreeNAS Ticket: #62055

STABLE: Fix bad default for sendmail and host_hostname

---

iocage_cli/__init__.py
iocage_cli/fstab.py
iocage_lib/ioc_common.py
iocage_lib/ioc_exceptions.py
iocage_lib/ioc_fstab.py

- Remove unused line
- Join multiline error messages with logit
- Create new exception class for inheritance
- Create reusable single instance of fstab
- Validates fstab before loading it now (unless using list, that's for users to spot the issues themselves)
- Check for duplicate entries
- Check if destination exists
- Check if source/destination is a directory
- Check if source/destination is an absolute path
- Check if dump/pass are single proper integers
Ticket: #61884

tkt-61884: Massive refactor of ioc_fstab

---

iocage_cli/fstab.py
iocage_lib/ioc_common.py
iocage_lib/ioc_exceptions.py
iocage_lib/ioc_fstab.py

git cherry-pick 325f8658d015d17e933d68654b0d0930c2ab0a8d
git cherry-pick e7bbf74afd968a644b1c04d3a9a8d3ed7b798fe7
git cherry-pick c539231ab3f0d3e6e729e19861dd61e64746b349
git cherry-pick 7ed168f4500f4bf1a42690f92c875cb14f2f35dd
git cherry-pick bbb0e2b2496a7bb3cb38bd65e3d7f8d5b5ce8409
git cherry-pick 107b14ec048dd9c703916233f6527cd8c5b52a42
- Remove unused line
- Join multiline error messages with logit
- Create new exception class for inheritance
- Create reusable single instance of fstab
- Validates fstab before loading it now (unless using list, that's for users to spot the issues themselves)
- Check for duplicate entries
- Check if destination exists
- Check if source/destination is a directory
- …

tkt-62334: Massive refactor of ioc_fstab (by skarekrow)

---

iocage_lib/ioc_json.py

Most users will want this behavior, with thin jails, it's an easy change to go and use none for most.
Ticket: #62361

tkt-62361: Migrate users to 'auto' with vnet_default_interface

---

iocage_lib/ioc_json.py

Same behavior, but property changed value. This will migrate them properly to auto, so when they go to 11.3, they will be OK. This code is U1 specific.
Ticket: #62361

tkt-62361: STABLE: Migrate users to 'auto' with vnet_default_interface

---

iocage_lib/ioc_start.py
iocage_lib/ioc_stop.py

This commit changes previous behaviour for iocage where now it tries to destroy network related setup if a jail is stopped with force flag set to true. However, in that case we suppress exceptions if any and move on.
Ticket: #61668

tkt-61668: Destroy Network related setup on stop (#713)

---

iocage_lib/ioc_create.py

This commit fixes a bug which prevented creating a template jail at the same time the jail was being created for the first time. The dataset was readonly at that point and system tried to complete the relevant configuration files but failed to do so because of the readonly property set to true.
Ticket: #62190

tkt-62190: Bug fix for template jails

---

iocage_lib/ioc_fetch.py
iocage_lib/iocage.py

- Remove doc.txz from default files
- Inform user we are downloading the MANIFEST if missing and using the default FreeBSD server
- No longer try to extract/verify files that are missing from the MANIFEST. This avoids the terrible behavior of then trying to redownload that file and reverify, which would only fail.
- No longer extract all files when a redownload of a dist has happened. This was exacerbated by the above issue.
- Don't extract if the user doesn't have a MANIFEST and uses custom server
Give the user a sane example that will work, not taking into account if they supplied other flags like --noupdate and such.
-Fix a few more remaining fetch bugs
A couple other long standing issues finally squashed:
- When a file was missing and extracted, no others would continue extracting
- …

tkt-63891: Fix a few issues in extraction/downloading code

---

iocage_cli/create.py
iocage_lib/ioc_common.py
iocage_lib/ioc_fetch.py

git cherry-pick 78fc998006de36de2e762fda991bfd689ad03b4d
Not a local file directory or custom mirror.
Closes: #626
FreeNAS Ticket: #64143

tkt-64323: Only capitalize fetch RELEASE if everything is default (by skarekrow)

---

iocage_lib/ioc_start.py

git cherry-pick 4f31f0f57114059825fdb556f3f621d63924b27d
- vnet0 was the only interface that renamed them to epairs, now all vnetN variants will (vnet0|ADDR,vnet1|ADDR, etc
- Add which nic inside the jail the vnet device on the host is associated with
- Only add default route to the first nic.
Closes #682
FreeNAS Ticket: #64113

tkt-64341: Fix creating additional epairs (by skarekrow)

---

iocage_lib/ioc_start.py

git cherry-pick 72e1c8473350d006d1970ac48683630316714a7b
- Fix missing decode()
- Add mtu to jail side of nic
Closes #661
FreeNAS Ticket: #64116

tkt-64350: Properly set mtu on all vnet interfaces (by skarekrow)

---

iocage_lib/ioc_plugin.py
iocage_lib/iocage.py

git cherry-pick 946056a9af10eeda4ff97f8c551865da83e5547e
Noted by @jsegaert
- Use the right interface for fetching instead of internal plumbing
- Fix bad variable usage
- Fix a couple other exceptions that could occur with the fetch interface
FreeNAS Ticket: #64638

tkt-64647: Fix mismatching RELEASEs being fetched, and a couple other bugs (by skarekrow)

---

iocage_lib/ioc_start.py
iocage_lib/ioc_stop.py

git cherry-pick 8e7d64dd90f54c12f8d8d7ce7328a1da29902360
This commit changes previous behaviour for iocage where now it tries to destroy network related setup if a jail is stopped with force flag set to true. However, in that case we suppress exceptions if any and move on.
Ticket: #61668

tkt-63306: Destroy Network related setup on stop (#713) (by sonicaj)

---

iocage_lib/ioc_list.py

Backport:
This commit improves exception handling for a case when we tried to determine a jail's ip address and failed to parse the output.
Ticket: #73975

tkt-73975: Improve exception handling for listing (#775)

---

iocage_lib/ioc_start.py

Otherwise we run into missing bridge_cmd's variable.
Ticket: #75648

tkt-75648: We now call the bridge_cmd if the variable is added

---

iocage_lib/ioc_start.py

Otherwise we run into missing bridge_cmd's variable.
Ticket: #75648
(cherry picked from commit f796d610767af14327fc2f07bbdaf317dfef9c8b)

We now call the bridge_cmd if the variable is added (#167)

---

iocage_lib/ioc_json.py

This is required to migrate users to auto with vnet_default_interface now that the version has been upgraded.
FreeNAS Ticket: #75648

tkt-75648: Correct when we update conf version and catch conf 14

---

iocage_lib/ioc_json.py

This commit resolves two naming conflicts where we used a variable before assigning it.
Ticket: #79311

tkt-79311: Naming conflicts

---

iocage_cli/fstab.py
iocage_lib/ioc_fstab.py
iocage_lib/iocage.py

Otherwise we end up getting false validation and mangling mounts with spaces in them.
FreeNAS Ticket: #76864

tkt-79797: Split on tabs for fstab  (by skarekrow)

---

iocage_lib/ioc_list.py

This commit adds a safety check for ensuring that if a user has made a dataset/zvol under templates/jails dataset, we raise a warning for that while listing jails/templates instead of raising a traceback.
Ticket: #81498

tkt-83291: Safety check for mountpoint prop (by sonicaj)

---

iocage_lib/ioc_list.py

This commit adds a safety check for ensuring that if a user has made a dataset/zvol under templates/jails dataset, we raise a warning for that while listing jails/templates instead of raising a traceback.
Ticket: #81498

tkt-83283: Safety check for mountpoint prop (by sonicaj)

---

.gitignore
iocage_lib/ioc_fstab.py
iocage_lib/ioc_start.py

git cherry-pick -x 67ceb4b6aa08d1804abbaf97ee2ae40311f6b19e
git cherry-pick -x 5e422e7a58d8d7f2665020b6e27837e4ff9fbcf4
git cherry-pick -x f0aa5b5e9abe9f698166b81a1137292e4837c8e1
git cherry-pick -x a6ddad0857037b62585d9a3a1de83079b678513b
git cherry-pick -x 3c9db255e90abbe7c58584055e3523014d493a76
This will replace the old iocage mountpoints (/mnt/iocage or /iocage) with the current structure (/mnt/POOL/iocage or /POOL/iocage) if the new source/destination directory exist.
This also corrects an issue with replacing an index not writing new line endings. We check these during all fstab operations except list, and during start.
NAS-101270

NAS-101270 / 11.2 / Replace old fstab locations  (by skarekrow)

---

iocage_lib/ioc_create.py

This is a “backport” of #65610
NAS-101623
Signed-off-by: Brandon Schneider <brandon@ixsystems.com>

NAS-101623 / 11.2 / Replace underscores in hostname

---

iocage_lib/ioc_fstab.py
iocage_lib/iocage.py

git cherry-pick -x 0a5d826161cb9d66835ae0264ad5c1a8809406f0
This commit introduces following changes:
1) Validate fstab entry when we replace ( the new changes - not the old ones ).
2) Validate destination directory exists
3) Fix an issue where on edit action we did nothing.
Ticket: #101525

NAS-101525 / 11.2 / Validate while replacing fstab entry (by sonicaj)

---

iocage_lib/ioc_list.py

This commit introduces changes which makes sure that in cases when default configuration is absent and the jail's configuration is corrupt too, we don't raise a traceback and create the default configuration file instead also making sure jails are listed correctly as corrupt.

NAS-102611 / 11.2 / Ensure default configuration existence

---

iocage_lib/ioc_plugin.py
requirements.txt
setup.py

This commit drops dulwich dependency and replaces it's usages with git python instead.

Drop dulwich dependency

---

iocage_lib/ioc_plugin.py

This commit decouples listing plugins from fetching plugin repo so that when plugin repo does not exist, a plugin install commands installs the plugin instead of listing available plugins.

NAS-102928 / 11.2 / Decouple listing plugins from fetching plugins repo

---

iocage_lib/ioc_create.py
iocage_lib/ioc_plugin.py

This commit makes sure that we don't stop/start a jail unnecessarily when installing a package. It is only stopped if it was started by iocage during pkg installation phase.
Also this commit removes a usage where we removed resolv.conf, i am unsure why we were doing that here at all but that is likely going to cause issues if the jail is already running and the user expects his resolv.conf to be there.

Make sure we don't stop/start jail unnecessarily

---

iocage_lib/ioc_json.py

This commit adds changes which ensure that we don't automatically activate a pool named as  like .

NAS-103179 / 12 / Skip boot-pool like freenas-boot (by sonicaj)

---

iocage_lib/dataset.py

If we have any dataset which is not mounted or is ZFS encrypted and doesn't have it's keys loaded, we skip it. Iocage handles creation/destruction of datasets itself and ideally the user should not manipulate these datasets on his/her own.

NAS-103669 / 12 / Native zfs encryption support (by sonicaj)

---

iocage_lib/ioc_start.py

This commit fixes an issue where stderr could be null if debug mode was enabled and we would try to decode it.

NAS-103587 / 11.3 / Correctly raise exception for failed jail start (by sonicaj)

---

iocage_lib/ioc_fstab.py

This PR fixes following bugs:
1) Iocage did not judge destinations correctly when attempting to correct malformed fstab
2) Iocage wrote python list to fstab if fstab file's contents were changed during validation.
3) Add /mnt/mnt to list of malformed mount points for fstab correction.

NAS-103568 / 11.3 / Bug fixes for fstab

---

iocage_lib/ioc_check.py
iocage_lib/resource.py
iocage_lib/zfs.py

This commit fixes an issue where we set the mount point as that of the parent if iocage's mount point didn't start with it. But if altroots are involved, they are added automatically to the mount point resulting in a misconfigured mount point.

NAS-103568 / 11.3 / Inherit mount point from parent (by sonicaj)

---

iocage_lib/cache.py

git cherry-pick -x 5b327274a7cb0a350e015d953d819af525102c07
This commit introduces locks for iocage cache which ensure that when iocage's api is being used, it's safe from cache.reset and cache.datasets/pools simultaneous calls

NAS-103581 / 11.3 / Introduce locks for iocage cache (by sonicaj)

---

iocage_cli/create.py
iocage_cli/fetch.py
iocage_lib/ioc_common.py
iocage_lib/ioc_fetch.py
iocage_lib/ioc_plugin.py
iocage_lib/iocage.py

This PR introduces changes which allow user to use higher minor version number jails. This is allowed by FreeBSD and is okay to do so.

NAS-103827 / 11.2 / Allow users to use higher minor version number jails

---

iocage_cli/create.py
iocage_cli/fetch.py
iocage_lib/ioc_common.py
iocage_lib/ioc_fetch.py
iocage_lib/ioc_plugin.py
iocage_lib/iocage.py
iocage_lib/release.py

This PR introduces changes which allow user to use higher minor version number jails. This is allowed by FreeBSD and is okay to do so.

NAS-103827 / 11.3 / Allow users to use higher minor version number jails (by sonicaj)

---

iocage_cli/create.py
iocage_cli/fetch.py
iocage_lib/ioc_common.py
iocage_lib/ioc_fetch.py
iocage_lib/ioc_plugin.py
iocage_lib/iocage.py
iocage_lib/release.py

This PR introduces changes which allow user to use higher minor version number jails. This is allowed by FreeBSD and is okay to do so.

NAS-103827 / 12 / Allow users to use higher minor version number jails (by sonicaj)

---

iocage_lib/ioc_json.py

This PR introduces changes which ensure we backup jail configurations before upgrading them. This way, users can manually restore if they want to downgrade a version.

NAS-103887 / 12 / Allow backups of jail configs before upgrade (by sonicaj)

---

iocage_lib/ioc_plugin.py
iocage_lib/ioc_upgrade.py
iocage_lib/iocage.py

This PR introduces following changes:
1) Fixes an issue where jid was not properly passed when upgrading plugins
2) Fixes an issue where wrong name for snapshot was used when trying to rollback during upgrade failure
3) Fixes an issue where iocage did not correctly log that a particular snapshot doesn't exist during rollback

NAS-104026 / 12 / Bug fixes for basejail upgrades (by sonicaj)

---

iocage_lib/ioc_json.py

This PR introduces changes which ensure we backup jail configurations before upgrading them. This way, users can manually restore if they want to downgrade a version.

NAS-103887 / 11.3 / Allow backups of jail configs before upgrade (by sonicaj)

---

iocage_lib/ioc_plugin.py
iocage_lib/ioc_upgrade.py
iocage_lib/iocage.py

This PR introduces following changes:
1) Fixes an issue where jid was not properly passed when upgrading plugins
2) Fixes an issue where wrong name for snapshot was used when trying to rollback during upgrade failure
3) Fixes an issue where iocage did not correctly log that a particular snapshot doesn't exist during rollback

NAS-104026 / 11.3 / Bug fixes for basejail upgrades (by sonicaj)

---

iocage_lib/ioc_fetch.py

This commit fixes an issue where iocage updated the complete configuration of jails on update for updating release property. This results in undesired behaviour with jails having partial configuration resulting in complete configuration and some properties are different when jail is running, i.e devfs_ruleset, that is changed as well.

NAS-104875 / 12.0 / Only update release property on update of jails

---

iocage_lib/ioc_fetch.py

This commit fixes an issue where iocage updated the complete configuration of jails on update for updating release property. This results in undesired behaviour with jails having partial configuration resulting in complete configuration and some properties are different when jail is running, i.e devfs_ruleset, that is changed as well.

NAS-104875 / 11.3 / Only update release property on update of jails (by sonicaj)

---

iocage_lib/ioc_fetch.py
iocage_lib/ioc_list.py
iocage_lib/ioc_plugin.py

This PR introduces following changes:
1) If we are unable to fetch a plugin's data from it's repository, we shouldn't error out and still list plugins which are fine. This is fixed in this.
2) Make skipping doc.txz okay when fetching a release as some release might not have it and the user still might have specified his/her desire for it.
3) Gracefully raise exception if INDEX does not exist for certain plugin repositories.

NAS-104846 / 12.0 / Listing Plugin Fixes

---

iocage_lib/ioc_json.py

This commit introduces changes to use plugin manifest name to determine plugin name instead of using the name entry in the manifest because some plugins might have a different name entry then the manifest file name which so far all plugins have similar to what they have in INDEX.

NAS-104894 / 12.0 / Use plugin manfiest names for determining plugin name

---

iocage_lib/ioc_fetch.py
iocage_lib/ioc_list.py
iocage_lib/ioc_plugin.py

This PR introduces following changes:
1) If we are unable to fetch a plugin's data from it's repository, we shouldn't error out and still list plugins which are fine. This is fixed in this.
2) Make skipping doc.txz okay when fetching a release as some release might not have it and the user still might have specified his/her desire for it.
3) Gracefully raise exception if INDEX does not exist for certain plugin repositories.

NAS-104846 / 11.3 / Listing Plugin Fixes (by sonicaj)

---

iocage_lib/ioc_json.py

This commit introduces changes to use plugin manifest name to determine plugin name instead of using the name entry in the manifest because some plugins might have a different name entry then the manifest file name which so far all plugins have similar to what they have in INDEX.

NAS-104894 / 11.3 / Use plugin manfiest names for determining plugin name (by sonicaj)

---

iocage_lib/cache.py
iocage_lib/zfs.py

This commit fixes an issue where we used to cache snapshots which resulted in exteremly slow iocage operation times.
Closes #1114

NAS-104930 / 12.0 / Donot cache snapshots for iocage (by sonicaj)

---

iocage_lib/cache.py
iocage_lib/zfs.py

This commit fixes an issue where we used to cache snapshots which resulted in exteremly slow iocage operation times.
Closes #1114

NAS-104930 / 11.3 / Donot cache snapshots for iocage (by sonicaj) (by bugclerk)

---

iocage_lib/ioc_common.py
iocage_lib/ioc_json.py
iocage_lib/ioc_start.py

git cherry-pick -x 4d5c3f8d1f902b0585cb01013b51458ddf96077b
git cherry-pick -x 9b2de95fcd362ee5a6235ec1a62805dfc4d80a8a
cloned/copied into dynamic ones.  This makes devfs rule handling more
symmetrical to what is done when the default ruleset 4 is configured (which
in fact never applies devfs ruleset 4, but creates an iocage specific
dynamic ruleset instead - which can be quite confusing).
As a result, this addresses the problem of non-dynamic rulesets being
removed on `iocage stop` raised in https://github.com/iocage/iocage/issues/952.
This also makes iocage fail to start a jail if the configured devfs ruleset
is not available - beforehand it would start with a default ruleset in this
case, which can have severe unwanted …

NAS-104777 / 12.0 / Change devfs ruleset handling so that configured rulesets != 4 are (by grembo) (by bugclerk)

---

iocage_lib/ioc_json.py

This PR introduces changes to ensure that the auto generated `mac_prefix` is valid in terms of it having the first bit in the first byte unset and the second bit in the first byte set.
Why we do this is because first bit `set` in the first byte represents multicast address from which a bridge is not able to learn and the second bit `set` represents local addresses which a jail is essentially. So we enforce this restriction now to make sure `mac_prefix` adheres to it.

NAS-105538 / 12.0 / Make sure mac_prefix is valid (by sonicaj)

---

iocage_lib/iocage.py

Earlier we used to restart rc's inside the jail but for dhcp based jails, that does not seem to work very well and we see issues where the services in plugins are not started properly.

NAS-105528 / 12.0 / Restart plugins after update (by sonicaj)

---

iocage_lib/ioc_plugin.py

git cherry-pick -x 7223094b42622b2a3932dd55fc5827964ef49a38
This PR introduces changes to ensure that if we have `ABI` provided in the plugin manifest's packagesite, we expand it keeping in line with the `release` plugin is using.

NAS-105608 / 12.0 / Make sure we handle ABI in packagesite gracefully (by sonicaj)

---

iocage_lib/ioc_json.py

git cherry-pick -x d3391aa06f84b8365d3251ae7b5eeee59a17a539
git cherry-pick -x e4e9d4d2f5db3e36d1fa789e323af97e0560a19c
This PR introduces changes to ensure that the auto generated `mac_prefix` is valid in terms of it having the first bit in the first byte unset and the second bit in the first byte set.
Why we do this is because first bit `set` in the first byte represents multicast address from which a bridge is not able to learn and the second bit `set` represents local addresses which a jail is essentially. So we enforce this restriction now to make sure `mac_prefix` adheres to it.

NAS-105538 / 11.3 / Make sure mac_prefix is valid (by sonicaj)

---

iocage_lib/iocage.py

Earlier we used to restart rc's inside the jail but for dhcp based jails, that does not seem to work very well and we see issues where the services in plugins are not started properly.

NAS-105528 / 11.3 / Restart plugins after update (by sonicaj)

---

.travis/flake8.sh
iocage_lib/ioc_plugin.py

git cherry-pick -x 7223094b42622b2a3932dd55fc5827964ef49a38
This PR introduces changes to ensure that if we have `ABI` provided in the plugin manifest's packagesite, we expand it keeping in line with the `release` plugin is using.

NAS-105608 / 11.3 / Make sure we handle ABI in packagesite gracefully (by sonicaj) (by bugclerk)

---

iocage_lib/ioc_plugin.py

While uninstalling a community plugin and reinstalling it with the same name there was a bug where the `overlay` folder didn't get applied to the fresh installed jail. The cause of this is probably a bug in the disutils library and how it caches the created folders.
During debugging and testing the following exception was raised: https://github.com/python/cpython/blob/master/Lib/distutils/dir_util.py#L73 but as it is ignored and not logged during the `copy_tree` call in `ioc_plugin.py` it was very hard to find what really happen (this is why I changed the try/except to log an exception and only copy it if the overlay folder exists).
The distutils exception was raised when it cached an overlay folder, shutil removed it during plugin removal and then while creating it again distutils …

NAS-105845 / 12.0 / Clean distutils dir cache before copy_tree (by fulder)

---

iocage_lib/ioc_fstab.py
iocage_lib/utils.py

This PR introduces changes to ensure that we accept and deal with any valid fstab file. Right now we expect the file to have encoded characters for spaces etc, this change makes sure that we accept whatever the underlying OS is going to accept making the fstab handing more robust

NAS-105735 / 12.0 / Use fstab.c to read fstab file contents (by sonicaj)

---

iocage_lib/ioc_plugin.py

While uninstalling a community plugin and reinstalling it with the same name there was a bug where the `overlay` folder didn't get applied to the fresh installed jail. The cause of this is probably a bug in the disutils library and how it caches the created folders.
During debugging and testing the following exception was raised: https://github.com/python/cpython/blob/master/Lib/distutils/dir_util.py#L73 but as it is ignored and not logged during the `copy_tree` call in `ioc_plugin.py` it was very hard to find what really happen (this is why I changed the try/except to log an exception and only copy it if the overlay folder exists).
The distutils exception was raised when it cached an overlay folder, shutil removed it during plugin removal and then while creating it again distutils …

NAS-105845 / 11.3 / Clean distutils dir cache before copy_tree (by fulder) (by bugclerk)

---

iocage_lib/ioc_fstab.py
iocage_lib/utils.py

This PR introduces changes to ensure that we accept and deal with any valid fstab file. Right now we expect the file to have encoded characters for spaces etc, this change makes sure that we accept whatever the underlying OS is going to accept making the fstab handing more robust

NAS-105735 / 11.3 / Use fstab.c to read fstab file contents (by sonicaj) (by bugclerk)

---

.cirrus.yml
iocage_lib/ioc_json.py
iocage_lib/ioc_start.py
tests/conftest.py
tests/unit_tests/1000_lib_start_test.py

git cherry-pick -x 5310084328dc8c410c1ed45ff9509ea6e1aad26a
git cherry-pick -x cccf979b4f0259ffc92142294f0f8a78f5cbc1f4
git cherry-pick -x 988d62066fd12472a57e14a3beab9755780e3e9c
git cherry-pick -x 1cce79ebcd6bd0abeee361c3e894fcf25fde8c31
git cherry-pick -x f2cc6568c978a3c971ca13935aab0a84bc962a4c
git cherry-pick -x 1181a81a85cbd49fbbc5916b8d4b50be033b6a55
git cherry-pick -x 760294893f2f856055f3186510dc4b6962b45c33
git cherry-pick -x 89499f3ea336665226f56c29b0f3de7839104b9c
git cherry-pick -x 717d7648ae98b5ff7a60232164169bdd4ec2a3d6
git cherry-pick -x 3473e6b33fa4a5530330665e5950543687caa8b0
git cherry-pick -x fae101d2d8decde7c3d60a51f849b2325fe817b2
git cherry-pick -x …

NAS-106037 / 12.0 / Make MTU of VNet interfaces configurable (by nathanjrobertson)

---

doc/source/plugins.rst
iocage_lib/ioc_common.py
iocage_lib/ioc_plugin.py
iocage_lib/ioc_start.py

This PR adds following changes :
1) Adds validation to ensure a plugin manifest is not malformed.
2) Makes sure that we are able to specify custom paths/includes for devfs ruleset generation for plugins in the plugin manifest.

NAS-106031 / 12.0 / Bug fixes for proper handling of custom devfs ruleset generation in plugins (by sonicaj)

---

iocage_lib/ioc_common.py
iocage_lib/ioc_json.py
iocage_lib/ioc_start.py

FreeBSD provides 0 as a default ruleset for mountpoints. Allow using 0 ruleset for jails.

NAS-106134 / 12.0 / Allow using 0 devfs ruleset (by sonicaj)

---

iocage_lib/ioc_common.py

NAS-106134 / 11.3 / Allow users to use 0 default devfs ruleset

---

iocage_lib/ioc_json.py

git cherry-pick -x 4e0d06d16a57b038fa3a1da620399c0dfdb9385f

NAS-106610 / 12.0 / Move plugins from official plugins list to community plugins (by sonicaj)

---

iocage_lib/ioc_plugin.py

Earlier we used to browse package listing but lately that changed and it's not possible to browse anymore. So this PR intends to do what `pkg` does and parses packagesite.txz contents to retrieve plugin versions.

NAS-106800 / 12.1 / Retrieve plugins version data from packagesite.txz (by sonicaj)

---

iocage_lib/ioc_plugin.py

Earlier we used to browse package listing but lately that changed and it's not possible to browse anymore. So this PR intends to do what `pkg` does and parses packagesite.txz contents to retrieve plugin versions.

NAS-106800 / 12.0 / Retrieve plugins version data from packagesite.txz (by sonicaj)

---

iocage_lib/ioc_plugin.py

Some pkgs have dependencies with versions listed and in this case the regex being used is unable to determine which version is actually the main pkg ones. We take a different approach and use path of the pkg to determine pkg version.

NAS-106822 / 12.1 / Use path to determine plugin version (by sonicaj)

---

iocage_lib/ioc_plugin.py

Some pkgs have dependencies with versions listed and in this case the regex being used is unable to determine which version is actually the main pkg ones. We take a different approach and use path of the pkg to determine pkg version.

NAS-106822 / 12.0 / Use path to determine plugin version (by sonicaj)

---

iocage_lib/ioc_create.py

If a package fails to install, we output subsequent successful package installation as failed whereas in reality they have not failed as the flag is being reused.

NAS-106965 / 12.1 / Make sure we don't mark a succcessful package installation as failed (by sonicaj)

---

iocage_lib/ioc_json.py

Fixes #1163
Fixes the regression reported as per #1163.  Both the Zoneminder and MineOS community plugins would like to leverage this functionality.  Can this please be ported to the FreeNAS/TrueNAS 12 branch?  
The issue manifests itself as follows:
1) In `iocage fetch`, the Admin Portal has linebreak in the post-install notes
```
➜  ~ sudo iocage fetch -P mineos.json -n mineos nat=1 --branch=experimental
Plugin: mineos
Official Plugin: False
Using RELEASE: 11.3-RELEASE
Using Branch: experimental
Post-install Artifact: https://github.com/jsegaert/iocage-plugin-mineos.git
These pkgs will be installed:
- sysutils/py-rdiff-backup
- sysutils/screen
- net/rsync
- devel/gmake
- devel/git-lite
- lang/python3
- …
```

NAS-107112 / 12.1 / Strip newline from plugin-properties (by jsegaert)

---

iocage_lib/ioc_create.py

When a jail is created, we set the hostname in rc.conf for each jail, however this means that the value specified in host.hostname never gets respected. So we should either be setting the hostname in rc file each time the jail starts or default to using host.hostname. I propose the latter as I think we should not be making decisions on the user's behalf where he/she might override it in rc.conf his/herself.

NAS-106984 / 12.1 / Donot set hostname in rc.conf (by sonicaj)

---

iocage_lib/ioc_create.py

When a jail is created, we set the hostname in rc.conf for each jail, however this means that the value specified in host.hostname never gets respected. So we should either be setting the hostname in rc file each time the jail starts or default to using host.hostname. I propose the latter as I think we should not be making decisions on the user's behalf where he/she might override it in rc.conf his/herself.

NAS-106984 / 12.0 / Donot set hostname in rc.conf (by sonicaj)

---

iocage_lib/ioc_create.py

When a jail is created, we set the hostname in rc.conf for each jail, however this means that the value specified in host.hostname never gets respected. So we should either be setting the hostname in rc file each time the jail starts or default to using host.hostname. I propose the latter as I think we should not be making decisions on the user's behalf where he/she might override it in rc.conf his/herself.

NAS-106984 / 11.3 / Donot set hostname in rc.conf (by sonicaj)

---

iocage_lib/ioc_create.py

If a package fails to install, we output subsequent successful package installation as failed whereas in reality they have not failed as the flag is being reused.

NAS-106965 / 11.3 / Make sure we don't mark a succcessful package installation as failed (by sonicaj)

---

iocage_lib/ioc_create.py

If a package fails to install, we output subsequent successful package installation as failed whereas in reality they have not failed as the flag is being reused.

NAS-106965 / 12.0 / Make sure we don't mark a succcessful package installation as failed (by sonicaj)

---

iocage_lib/ioc_json.py

Fixes #1163
Fixes the regression reported as per #1163.  Both the Zoneminder and MineOS community plugins would like to leverage this functionality.  Can this please be ported to the FreeNAS/TrueNAS 12 branch?  
The issue manifests itself as follows:
1) In `iocage fetch`, the Admin Portal has linebreak in the post-install notes
```
➜  ~ sudo iocage fetch -P mineos.json -n mineos nat=1 --branch=experimental
Plugin: mineos
Official Plugin: False
Using RELEASE: 11.3-RELEASE
Using Branch: experimental
Post-install Artifact: https://github.com/jsegaert/iocage-plugin-mineos.git
These pkgs will be installed:
- sysutils/py-rdiff-backup
- sysutils/screen
- net/rsync
- devel/gmake
- devel/git-lite
- lang/python3
- …
```

NAS-107112 / 12.0 / Strip newline from plugin-properties (by jsegaert)

---

iocage_lib/zfs.py

Some users might have `listsnapshots` property enabled on a pool which will result in changed behaviour of`zfs list` listing snapshots by default unless explicitly filtered out.
Original PR: https://github.com/iocage/iocage/pull/1201

NAS-107164 / 12.1 / Default to only retrieving datasets (by sonicaj)

---

iocage_lib/zfs.py

Some users might have `listsnapshots` property enabled on a pool which will result in changed behaviour of`zfs list` listing snapshots by default unless explicitly filtered out.
Original PR: https://github.com/iocage/iocage/pull/1201

NAS-107164 / 12.0 / Default to only retrieving datasets (by sonicaj)

---

iocage_lib/cache.py

When using iocage's library it's possible that the consumer resets the cache and another thread is in the middle of accessing it resulting in undesired behaviour.
Original PR: https://github.com/iocage/iocage/pull/1207

NAS-107433 / 12.0 / Correctly handle locks for eliminating a new race condition (by sonicaj)

---

iocage_lib/ioc_stop.py

Earlier iocage unconditionally checked cloned devfs ruleset on each jail listing, that behaviour has changed due to performance reasons and now we explicilty get cloned devfs ruleset where desired.
Original PR: https://github.com/iocage/iocage/pull/1209

NAS-107486 / 12.0 / Correctly identify devfs ruleset on stopping jail (by sonicaj)

---

iocage_lib/dataset.py

Users can likely have thousands of snapshots which if we cache takes precious time. Snapshot related tasks are quite a few and are mostly used by CLI users as middleware does not consume that interface.

NAS-107687 / 12.0 / Donot use cache for snapshot resource

---

iocage_lib/ioc_plugin.py

This PR fixes an issue where if the packagesite does not use ABI keyword and the new plugin manifest uses a newer freebsd release, the upgrade will fail because jail is not restarted during the process and is still active using the old release when `update` executes.
This behaviour introduces 2 more issues where packagesite using ABI will pull packages from the old release version resulting in `apparently` upgraded plugin but in reality using old ABI plugin packages. The other issue is execution of pre update script which should actually happen before the upgrade.

NAS-108130 / 12.0 / Fix upgrades for plugins using a higher release and a different packagesite

---

iocage_lib/cache.py

In a situation where there are multiple pools both showing up as activated for iocage and one of the pools is umounted, that results in cache and iocage pool logic getting out of sync resuling in various errors

NAS-108747 / 12.0 / Handle case where pool may not be mounted

---

iocage_lib/ioc_fstab.py

This commit introduces changes to normalize jail root if it has special characters like spaces so that we make an equal/valid comparison with values

NAS-109587 / 12.0 / Normalize jail root attribute in fstab

---

iocage_lib/ioc_destroy.py

This commit fixes an issue where we do not fail at deleting a misconfigured jail which does not has it's configuration file present.

NAS-109778 / 12.0 / Don't fail at deleting misconfigured jail

---

iocage_lib/ioc_plugin.py

I'm tracking a memory leak in `middlewared` service. I've written a method to use the `tracemalloc` module to track allocated memory. Immediately I noticed that we're using 160MB+ memory on `middlewared` startup and it's because we're loading the yaml file entirely into memory "`read()`" (as 1 big string) and then iterating over every line "`strip('\n')`".
Furthermore, this file is already stored on `tmpfs` which is using memory already so we're potentially using 2-3x the memory unnecessarily.
My change is simple, don't load the file into RAM (since it's already there on tmpfs), simply iterate over the file itself.
Before the change:
`[2021/05/18 05:27:59] (DEBUG) middlewared._tracemalloc_start():1412 - #1: /usr/local/lib/python3.9/site-packages/iocage_lib/ioc_plugin.py:167: size=163 MiB …

NAS-110691 / 12.0 / fix HUGE memory allocation on middlewared startup

---

iocage_lib/ioc_plugin.py

This commit adds changes to adapt regext to accept new format specified by upstream freebsd pkg but still support the old one as it's being used by us for packagesites which are hosted by us.

NAS-111775 / 12.0 / Update version matching regex for plugins

---

iocage_lib/zfs.py

ZFS allows trailing whitespace for zpool names. A horrible decision, in my opinion, but the fact remains it's allowed. Mostly we see this happen by accident. When this occurs, iocage explodes because it strips the trailing whitespace in the `all_properties()` function which essentially breaks everything. This fixes it to not `strip()` whitespace from the zpool name.

NAS-113392 / 12.0 / fix all_properties() stripping whitespace

---

iocage_lib/ioc_plugin.py

This commit adds changes to upgrade implementation of plugin to make sure we update plugin artifact before trying to upgrade. Motivation behind this change is that we are going to try to execute pre update hook but without updating the artifact from upstream, we won't have the latest changes upstream wanted resulting in a potential inconsistent upgrade.

NAS-113813 / 12.0 / Update plugin artifact before executing pre update script

---

iocage_lib/create_utils.py
iocage_lib/ioc_create.py
iocage_lib/ioc_plugin.py

This PR adds changes for plugin jails to convert them to basejails when the plugin is upgraded if it's not already a basejail. This case wouldn't ideally happen unless for some users who are running our migrated version of asigra plugin where the jail is not a basejail.

NAS-113823 / 12.0 / Make plugin jail a base jail if it's not already a basejail

---

iocage_lib/ioc_fetch.py

Catch ConnectionError to provide somewhat readable feedback to end user:
```python
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
return self.connection.recv_into(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/OpenSSL/SSL.py", line 1822, in recv_into
self._raise_ssl_error(self._ssl, result)
File "/usr/local/lib/python3.9/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (54, 'ECONNRESET')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```

NAS-113492 / 22.02 / Add readable message on connection error
